version: '3.7'

services:
    elixir:
        image: elixir
        container_name: elixir-elx-test1
        volumes:
            - ./app:/app
        ports:
            - "8080:8080"
        tty: true
    redis:
        image: redis
        container_name: redis-elx-test1
        command: redis-server